apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bloop.fullname" . }}
  annotations:
    secret.reloader.stakater.com/reload: "{{ include "bloop.fullname" . }}"
  labels:
    {{- include "bloop.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "bloop.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "bloop.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      initContainers:
        - name: prepare-folders
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          image: "alpine:3.14"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
          - /bin/sh
          args:
          - -c
          - "mkdir /data/repos -p"
          volumeMounts:
          - name: {{ include "bloop.fullname" . }}-storage
            mountPath: /data
      containers:
        - name: {{ .Chart.Name }}-app
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
          - /bleep
          args:
          - --host=0.0.0.0
          - --source-dir=/data/repos
          - --index-dir=/data/index
          - --model-dir=/model
          - --dylib-dir=/dylib
          - --frontend-dist=/frontend
          - --collection-name={{ .Values.qdrant.collectionName }}
          - --max-threads={{ .Values.bloop.maxThreads }}
          - --answer-api-url={{ .Values.bloop.answerApiUrl }}
          - --qdrant-url={{ .Values.qdrant.url }}
          - --embedding-server-url={{ .Values.bloop.embeddingServerUrl }}:8080
          - --embedding-batch-size={{ .Values.bloop.embeddingBatchSize }}
          - --instance-domain={{ .Values.bloop.instanceDomain }}
          - --cognito-userpool-id={{ .Values.bloop.cognitoUserpoolId }}
          - --cognito-client-id={{ .Values.bloop.cognitoClientId }}
          - --cognito-mgmt-url={{ .Values.bloop.cognitoMgmtUrl }}
          - --cognito-auth-url={{ .Values.bloop.cognitoAuthUrl }}
          - --bloop-instance-secret={{ .Values.bloop.bloopInstanceSecret }}
          - --bloop-instance-org={{ .Values.bloop.githubOrgName }}
          - --analytics-key={{ .Values.bloop.analyticsKey }}
          - --analytics-data-plane={{ .Values.bloop.analyticsDataPlane }}
          - --sentry-dsn={{ .Values.bloop.sentryDsn }}
          - --sentry-dsn-fe={{ .Values.bloop.sentryDsnFE }}
          - --analytics-key-fe={{ .Values.bloop.analyticsKeyFE }}
          - --disable-log-write
          env:
          - name: BLOOP_LOG
            value: {{ .Values.bloop.logLevel }}
          {{ if .Values.env }}
          {{ range .Values.env }}
          -
          {{- . | toYaml | nindent 12 -}}
          {{ end }}
          {{ end }}
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /api/health
              port: 7878
            initialDelaySeconds: 20
            periodSeconds: 5
          volumeMounts:
          - name: {{ include "bloop.fullname" . }}-storage
            mountPath: /data
          - mountPath: "/app/secrets"
            name: {{ include "bloop.fullname" . }}
            readOnly: true
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: {{ include "bloop.fullname" . }}
          secret:
            secretName: {{ include "bloop.fullname" . }}
        - name: {{ include "bloop.fullname" . }}-storage
          persistentVolumeClaim:
            claimName: {{ include "bloop.fullname" . }}-storage
