name: Update Documentation

on:
  push:
    branches: [main]
    paths:
      - "server/**"
      - ".github/workflows/server**"
      - ".github/workflows/documentation.yml"
      - "scripts/start-server.sh"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "bloop"

      - name: Start webserver and fetch OpenAPI
        run: |
          bash ${GITHUB_WORKSPACE}/scripts/start-server.sh
          mkdir temp_openapi
          cp server/bleep/src/query/grammar.pest temp_openapi/grammar.pest
          cd temp_openapi
          curl http://localhost:7878/api-doc/openapi.json --output openapi.json
        shell: bash

      - name: Push to another api-docs repository
        uses: cpina/github-action-push-to-another-repository@9e487f29582587eeb4837c0552c886bb0644b6b9
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: "temp_openapi"
          destination-github-username: "BloopAI"
          destination-repository-name: "bloop-api-docs"
          target-branch: main
          target-directory: "auto_update_openapi"
          user-email: "louis@bloop.ai"
          user-name: "stunningpixels"
